### ISSUE TITLE
Pattern matching of benchmarks does not work as described in README.

### ISSUE THREAD

**Issue by Vetii** [DiegoEliasCosta/CollectionsBench#1]
Hello, 

I am trying to use the CollectionsBench for my research, and the command `java -jar benchmarks.jar "JDK_Integer_ArrayList_.*"` that is described in the README returns:

```
No matching benchmarks. Miss-spelled regexp?
Use EXTRA verbose mode to debug the pattern matching.
``` 

I tried adding `-v EXTRA` to debug the matching, and the classes names do not seem to match the pattern `[LIBRARY]_[DATATYPE]_[COLLECTIONTYPE]_Test.java"` described in the README.

For instance, `java -jar benchmarks.jar -l "JDK"` returns:
```
Benchmarks: 
de.heidelberg.pvs.container_bench.benchmarks.singleoperations.lists.JDKListBench.bench
```
Calling `java -jar benchmarks.jar "JDKListBench*"` works. However, is it possible to run the same benchmark described int the readme?

**Comment by DiegoEliasCosta** [comment]
Hi Vetti,

we are currently doing on a huge refactor on the benchmark structure, to add more classes, more benchmarks and a better parameter support to specify the target benchmark.
Unfortunately, the README was not properly updated with the new standard. I might do this in the next few days.

If you want to run the tests as before (and as stated in the documentation), you can simply use the branch **icpe-2017**, where the class names still follow the old format.

**Comment by Vetii** [comment]
Ok, I am going to close it then.
